name: Release package

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:
    branches:
      - master

env:
  CTAN_URL: https://mirrors.rit.edu/CTAN
  TL_PACKAGES: alphalph auxhook background booktabs caption cm-unicode colortbl csquotes ctex diagbox emptypage enumitem everypage fancyvrb fandol floatrow footmisc hologo hycolor hypdoc hyperref l3build latexmk lexend libertinus-fonts listings lm-math makecell makeindex mathtools multirow ninecolors pict2e poormanlog preview psnfss siunitx setspace symbol tex-gyre tex-gyre-math tabularray threeparttable translator underscore unicode-math url xint xits xstring zhlineskip zref

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    env:
      SET_PATH: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set Version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Install TeX Live
        run: |
          ${{ env.SET_PATH }}
          wget ${{ env.CTAN_URL }}/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -xzf install-tl-unx.tar.gz
          cd install-tl-20* && ./install-tl --profile ../.github/workflows/texlive.profile
          tlmgr install ${{ env.TL_PACKAGES }}
          tlmgr update --self --all --no-auto-install --repository=${{ env.CTAN_URL }}/systems/texlive/tlnet/

      - name: Install fonts
        run: |
          mkdir fonts
          wget https://github.com/adobe-fonts/source-han-serif/raw/release/OTF/SimplifiedChinese/SourceHanSerifSC-SemiBold.otf
          wget https://github.com/adobe-fonts/source-han-serif/raw/release/OTF/SimplifiedChinese/SourceHanSerifSC-Bold.otf
          wget https://github.com/adobe-fonts/source-han-serif/raw/release/OTF/SimplifiedChinese/SourceHanSerifSC-Heavy.otf
          wget https://github.com/be5invis/Iosevka/releases/download/v15.6.3/ttf-iosevka-15.6.3.zip
          unzip ttf-iosevka-15.6.3.zip
          cp *.otf                   /usr/share/fonts/
          cp iosevka-lightitalic.ttf /usr/share/fonts/
          cp iosevka-light.ttf       /usr/share/fonts/
          cp iosevka-semibold.ttf    /usr/share/fonts/
          chmod -x /usr/share/fonts/*.otf
          chmod -x /usr/share/fonts/*.ttf
          fc-cache -fv

      - name: Zip CTAN package
        run: |
          ${{ env.SET_PATH }}
          l3build ctan
          mv njuvisual-ctan.zip njuvisual-ctan-$VERSION.zip
          cp build/doc/njuvisual.pdf njuvisual-$VERSION.pdf

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            njuvisual-v*.pdf
            njuvisual-ctan-v*.zip
